application:
  name: jobitapi
  project: jobit
  publicly_accessible: true
databases:
- type: postgresql
  version: "12.5"
  name: jobsapi
routers:
- name: main
  routes:
  - application_name: jobitapi
    paths:
    -/*